language: python
cache: pip
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
matrix:
  exclude:
    - python: 3.3
      env: DJANGO="Django>=1.9,<1.10"
    - python: 3.3
      env: DJANGO="Django>=1.10,<1.11"
install:
  - pip install $DJANGO
  - pip install -e .
  - pip install -r requirements.txt
before_script:
  - flake8
script:
  - coverage run runtests.py
  - coverage report -m
after_success:
  - coveralls --verbose
